-- Migration 049: Full SCA cases to reach 150 total full cases
-- Run after 037, 039, 041, 042. Adds 50 new full cases (12 min, actor script, marking criteria).
-- If you have ~100 full cases after dedup, total full after this: 150.

-- =====================================================
-- CASE: Recurrent Migraine
-- =====================================================
INSERT INTO sca_cases (
  title, category, category_code, scenario, patient_info, case_notes, actor_info, actor_behaviour,
  case_type, time_limit, difficulty, key_points, model_answer, is_pro, published, marking_criteria
) VALUES (
  'Recurrent Migraine',
  'Neurology',
  'FC-001',
  'You are a GP. A 34-year-old woman, Ms. Rachel Holt, has booked a face-to-face appointment. She has had recurrent headaches for 2 years and wants to discuss prevention.',
  '{"name": "Ms. Rachel Holt", "age": 34, "gender": "Female"}',
  '{"patient": "Ms. Rachel Holt", "age": 34, "gender": "Female", "pmh": "None", "medications": "Sumatriptan PRN", "allergies": "None", "social_summary": "Teacher, non-smoker", "family_summary": "Mother has migraine"}',
  '{"opening_statement": "Doctor, I get these awful headaches every few weeks. The triptan helps when I take it early but I want to know if there is something to prevent them.", "freely_given_history": {"presenting_complaint": "Recurrent headaches, throbbing, one side, with nausea. Last 4–24 hours.", "psychosocial_impact": "Missing work sometimes.", "ice": {"ideas": "Worried it might be something serious", "concerns": "Wants to reduce frequency", "expectations": "Hopes for preventive treatment"}}, "history_on_direct_questioning": {"frequency": "2–3 per month", "triggers": "Stress, lack of sleep", "aura": "No visual disturbance", "red_flags": "No sudden onset, no worst ever, no fever"}}',
  'ANXIOUS but articulate. Wants a clear plan. If doctor discusses prevention (e.g. propranolol, topiramate, lifestyle), show interest.',
  'full', 720, 'medium',
  ARRAY['Migraine diagnosis', 'Trigger and diary', 'Acute vs preventive treatment', 'Lifestyle', 'Safety-netting'],
  '## Model Approach\n\n**Key:** Confirm migraine (history, red flags). Discuss trigger diary, lifestyle (sleep, stress). Acute: triptan, NSAID. Preventive: propranolol or topiramate if frequent. Safety-net: sudden/worst ever headache, focal signs.',
  false, true,
  '{"domain1": {"title": "Domain 1: Data Gathering & Interpretation", "items": ["Established presenting complaint clearly", "Explored headache characteristics and frequency", "Obtained relevant past medical history", "Obtained drug history", "Explored ICE thoroughly", "Assessed red flags", "Obtained family history"]}, "domain2": {"title": "Domain 2: Clinical Management (Weighted 1.5x)", "items": ["Considered migraine vs other headache", "Discussed acute and preventive options", "Provided clear safety-netting", "Arranged follow-up", "Documented appropriately"]}, "domain3": {"title": "Domain 3: Interpersonal Skills", "items": ["Demonstrated empathy", "Used clear language", "Listened actively", "Involved patient in decisions", "Maintained professional manner"]}}'
);

-- =====================================================
-- CASE: New Type 2 Diabetes
-- =====================================================
INSERT INTO sca_cases (
  title, category, category_code, scenario, patient_info, case_notes, actor_info, actor_behaviour,
  case_type, time_limit, difficulty, key_points, model_answer, is_pro, published, marking_criteria
) VALUES (
  'New Type 2 Diabetes',
  'Endocrinology',
  'FC-002',
  'You are a GP. A 52-year-old man, Mr. Ian Moss, has been told his HbA1c is 58 (diabetes range). He has come to discuss what this means and what to do next.',
  '{"name": "Mr. Ian Moss", "age": 52, "gender": "Male"}',
  '{"patient": "Mr. Ian Moss", "age": 52, "gender": "Male", "pmh": "Hypertension", "medications": "Amlodipine 5mg", "allergies": "None", "social_summary": "Office job, BMI 31", "family_summary": "Father had diabetes"}',
  '{"opening_statement": "The nurse said my sugar is high and I have diabetes. I feel fine – do I really need to do anything?", "freely_given_history": {"presenting_complaint": "No symptoms. Shocked by diagnosis.", "ice": {"ideas": "Worried about tablets and complications", "concerns": "Can he reverse it?", "expectations": "Wants clear advice"}}, "history_on_direct_questioning": {"diet": "Eats takeaways 3–4 times per week", "exercise": "Little", "smoking": "No", "alcohol": "10–15 units/week"}}',
  'Slightly defensive but willing to listen. Responds well to clear, non-judgmental advice.',
  'full', 720, 'medium',
  ARRAY['Explain diagnosis', 'Lifestyle first', 'Metformin', 'Retinal and foot check', 'Follow-up'],
  '## Model Approach\n\n**Key:** Explain T2DM and importance of control. Lifestyle: diet, weight, exercise. Metformin first line. Arrange retinal screening and foot check. Diabetes education. Follow-up.',
  false, true,
  '{"domain1": {"title": "Domain 1: Data Gathering & Interpretation", "items": ["Established understanding of diagnosis", "Explored lifestyle", "Obtained PMH and medications", "Explored ICE", "Assessed cardiovascular risk"]}, "domain2": {"title": "Domain 2: Clinical Management (Weighted 1.5x)", "items": ["Explained diagnosis and targets", "Discussed lifestyle and metformin", "Arranged retinal and foot check", "Arranged follow-up", "Documented appropriately"]}, "domain3": {"title": "Domain 3: Interpersonal Skills", "items": ["Demonstrated empathy", "Non-judgmental approach", "Clear explanation", "Involved patient in plan"]}}'
),

('Chronic Low Back Pain', 'Musculoskeletal', 'FC-003',
  'You are a GP. A 48-year-old man, Mr. David Peel, has had low back pain for 3 months. He has tried physio and ibuprofen. Wants to know what else can be done.',
  '{"name": "Mr. David Peel", "age": 48, "gender": "Male"}',
  '{"patient": "Mr. David Peel", "age": 48, "gender": "Male", "pmh": "None", "medications": "Ibuprofen PRN", "allergies": "None", "social_summary": "Desk job", "family_summary": "None"}',
  '{"opening_statement": "My back has been killing me for months. Physio helped a bit but it keeps coming back. Is there anything stronger or do I need a scan?", "freely_given_history": {"presenting_complaint": "Central low back pain, no leg symptoms.", "ice": {"ideas": "Worried about disc", "concerns": "Wants to work", "expectations": "Scan or stronger treatment"}}, "history_on_direct_questioning": {"red_flags": "No cauda equina, no weight loss", "work": "Desk job"}}',
  'Frustrated but cooperative. Responds to clear explanation of NICE back pain pathway.',
  'full', 720, 'easy',
  ARRAY['NICE back pain', 'Red flags', 'Physio and analgesia', 'Avoid routine imaging', 'Safety-netting'],
  '## Model Approach\n\n**Key:** Exclude red flags. NICE: continue physio, analgesia; avoid routine imaging. Reassure. Safety-net.',
  false, true,
  '{"domain1": {"title": "Domain 1: Data Gathering & Interpretation", "items": ["Established presenting complaint", "Explored pain and red flags", "Obtained PMH", "Explored ICE"]}, "domain2": {"title": "Domain 2: Clinical Management (Weighted 1.5x)", "items": ["Applied NICE back pain pathway", "Avoided routine imaging", "Safety-netting", "Follow-up"]}, "domain3": {"title": "Domain 3: Interpersonal Skills", "items": ["Empathy", "Clear explanation", "Involved patient"]}}'
),

('Request for Sleeping Tablets', 'Mental Health', 'FC-004',
  'You are a GP. A 58-year-old woman, Mrs. Sandra Quick, has had insomnia for 2 months. She wants something to help her sleep. Stressed about family issues.',
  '{"name": "Mrs. Sandra Quick", "age": 58, "gender": "Female"}',
  '{"patient": "Mrs. Sandra Quick", "age": 58, "gender": "Female", "pmh": "None", "medications": "None", "allergies": "None", "social_summary": "Caring for ill mother", "family_summary": "None"}',
  '{"opening_statement": "I just need something to help me sleep. I lie there for hours. I have heard zopiclone works.", "freely_given_history": {"presenting_complaint": "Difficulty falling asleep, stress.", "ice": {"ideas": "Wants tablets", "concerns": "Worried about dependency", "expectations": "Short-term help"}}, "history_on_direct_questioning": {"caffeine": "Tea until 8pm", "routine": "Variable", "mood": "Stressed, not low"}}',
  'Anxious, keen for a quick fix. Receptive to sleep hygiene if offered with short-term option.',
  'full', 720, 'easy',
  ARRAY['Sleep hygiene', 'CBT-I', 'Short-term hypnotic only if needed', 'Safety-netting'],
  '## Model Approach\n\n**Key:** Sleep hygiene, address stress. CBT-I first line. Hypnotic only short-term if severe. Safety-net.',
  false, true,
  '{"domain1": {"title": "Domain 1: Data Gathering & Interpretation", "items": ["Established complaint", "Explored sleep and stress", "Explored ICE"]}, "domain2": {"title": "Domain 2: Clinical Management (Weighted 1.5x)", "items": ["Sleep hygiene", "CBT-I", "Limited hypnotic", "Safety-netting"]}, "domain3": {"title": "Domain 3: Interpersonal Skills", "items": ["Empathy", "Clear advice"]}}'
),

('Child with Earache', 'Paediatrics', 'FC-005',
  'You are a GP. The mother of 4-year-old Tom has brought him in with earache for 2 days. He has had a cold. No fever today. Drinking and playing.',
  '{"name": "Tom", "age": 4, "gender": "Male"}',
  '{"patient": "Tom", "age": 4, "gender": "Male", "pmh": "None", "medications": "None", "allergies": "None", "social_summary": "Nursery", "family_summary": "None"}',
  '{"opening_statement": "He has been pulling his ear and crying. I gave him Calpol. Should he have antibiotics?", "freely_given_history": {"presenting_complaint": "Earache, cold.", "ice": {"ideas": "Ear infection", "concerns": "Wants to avoid antibiotics if possible", "expectations": "Clear advice"}}, "history_on_direct_questioning": {"fever": "Had fever, better today", "feeding": "Drinking", "red_flags": "No rash, no neck stiffness"}}',
  'Mother anxious but informed. Wants clear advice.',
  'full', 720, 'easy',
  ARRAY['Acute otitis media', 'Watchful waiting vs antibiotics', 'Pain relief', 'Safety-netting'],
  '## Model Approach\n\n**Key:** AOM – most resolve without antibiotics. Pain relief (paracetamol/ibuprofen). Safety-net: worsening, fever, rash. Antibiotics if systemically unwell or high risk.',
  false, true,
  '{"domain1": {"title": "Domain 1: Data Gathering & Interpretation", "items": ["Established complaint", "Explored symptoms and red flags", "Explored ICE"]}, "domain2": {"title": "Domain 2: Clinical Management (Weighted 1.5x)", "items": ["AOM management", "Pain relief", "Safety-netting"]}, "domain3": {"title": "Domain 3: Interpersonal Skills", "items": ["Empathy", "Parental reassurance"]}}'
),

('Hypertension Review', 'Cardiovascular', 'FC-006',
  'You are a GP. A 62-year-old man, Mr. Frank Reid, is here for his annual hypertension review. His home readings have been 145–155/88–92. On amlodipine 5mg.',
  '{"name": "Mr. Frank Reid", "age": 62, "gender": "Male"}',
  '{"patient": "Mr. Frank Reid", "age": 62, "gender": "Male", "pmh": "Hypertension, T2DM", "medications": "Amlodipine 5mg, Metformin", "allergies": "None", "social_summary": "Retired, ex-smoker", "family_summary": "Father stroke at 70"}',
  '{"opening_statement": "The nurse said my blood pressure is still a bit high. Do I need another tablet?", "freely_given_history": {"presenting_complaint": "BP above target.", "ice": {"ideas": "Worried about stroke", "concerns": "More tablets", "expectations": "Clear plan"}}, "history_on_direct_questioning": {"compliance": "Takes regularly", "lifestyle": "Trying to lose weight", "symptoms": "None"}}',
  'Cooperative. Wants to avoid more medication if possible but will take if needed.',
  'full', 720, 'easy',
  ARRAY['BP target', 'Lifestyle', 'Step-up if needed', 'CV risk', 'Follow-up'],
  '## Model Approach\n\n**Key:** Confirm BP target (e.g. <140/90). Lifestyle. Consider adding ACEi/ARB if above target. CV risk discussion. Follow-up.',
  false, true,
  '{"domain1": {"title": "Domain 1: Data Gathering & Interpretation", "items": ["Established BP and compliance", "Explored lifestyle", "Explored ICE"]}, "domain2": {"title": "Domain 2: Clinical Management (Weighted 1.5x)", "items": ["BP target", "Step-up if needed", "Follow-up"]}, "domain3": {"title": "Domain 3: Interpersonal Skills", "items": ["Clear explanation", "Involved patient"]}}'
),

('Request for Sick Note', 'General Practice', 'FC-007',
  'You are a GP. A 29-year-old woman, Ms. Helen Stone, is asking for a fit note for 2 weeks off work. She has been low and anxious. Has had time off already.',
  '{"name": "Ms. Helen Stone", "age": 29, "gender": "Female"}',
  '{"patient": "Ms. Helen Stone", "age": 29, "gender": "Female", "pmh": "Anxiety", "medications": "Sertraline 50mg", "allergies": "None", "social_summary": "Office job", "family_summary": "None"}',
  '{"opening_statement": "I need a sick note for work. I have been signed off for 2 weeks already but I am not ready to go back. My mood is still low.", "freely_given_history": {"presenting_complaint": "Low mood, anxiety.", "ice": {"ideas": "Needs more time", "concerns": "Work pressure", "expectations": "2 more weeks"}}, "history_on_direct_questioning": {"mood": "Low", "risk": "No suicidal ideation", "support": "CBT waiting list"}}',
  'Anxious, defensive about work. Wants note but also support.',
  'full', 720, 'easy',
  ARRAY['Assess fitness', 'Sick note rules', 'Support', 'Return to work', 'Documentation'],
  '## Model Approach\n\n**Key:** Assess current fitness. Issue note if unfit. Discuss support (CBT, meds). Plan for return. Document reason.',
  false, true,
  '{"domain1": {"title": "Domain 1: Data Gathering & Interpretation", "items": ["Established mood and function", "Explored ICE", "Risk assessment"]}, "domain2": {"title": "Domain 2: Clinical Management (Weighted 1.5x)", "items": ["Fitness for work", "Note if appropriate", "Support", "Documentation"]}, "domain3": {"title": "Domain 3: Interpersonal Skills", "items": ["Empathy", "Non-judgmental"]}}'
),

('Palpitations', 'Cardiology', 'FC-008',
  'You are a GP. A 44-year-old woman, Ms. Jane Todd, has had intermittent palpitations for 3 weeks. Last a few seconds. No syncope. Stressed at work.',
  '{"name": "Ms. Jane Todd", "age": 44, "gender": "Female"}',
  '{"patient": "Ms. Jane Todd", "age": 44, "gender": "Female", "pmh": "None", "medications": "None", "allergies": "None", "social_summary": "Manager, 4 coffees/day", "family_summary": "No cardiac history"}',
  '{"opening_statement": "My heart sometimes races for a few seconds. It frightens me. Could it be my heart?", "freely_given_history": {"presenting_complaint": "Palpitations, brief.", "ice": {"ideas": "Worried about heart", "concerns": "Serious?", "expectations": "Reassurance or tests"}}, "history_on_direct_questioning": {"syncope": "No", "chest_pain": "No", "family": "No sudden death"}}',
  'Anxious. Relieved if benign explanation and simple plan.',
  'full', 720, 'easy',
  ARRAY['Benign vs serious', 'ECG', 'Caffeine and stress', 'Safety-netting'],
  '## Model Approach\n\n**Key:** Often benign (caffeine, stress). Red flags: syncope, chest pain, family history. ECG if indicated. Reassure. Safety-net.',
  false, true,
  '{"domain1": {"title": "Domain 1: Data Gathering & Interpretation", "items": ["Established complaint", "Red flags", "Explored ICE"]}, "domain2": {"title": "Domain 2: Clinical Management (Weighted 1.5x)", "items": ["ECG if indicated", "Reassurance", "Safety-netting"]}, "domain3": {"title": "Domain 3: Interpersonal Skills", "items": ["Empathy", "Clear explanation"]}}'
),

('Recurrent Thrush', 'Women''s Health', 'FC-009',
  'You are a GP. A 28-year-old woman, Ms. Kate Vine, has had four episodes of thrush in 6 months. Each time treated with clotrimazole. Wants long-term solution.',
  '{"name": "Ms. Kate Vine", "age": 28, "gender": "Female"}',
  '{"patient": "Ms. Kate Vine", "age": 28, "gender": "Female", "pmh": "None", "medications": "COCP", "allergies": "None", "social_summary": "Teacher", "family_summary": "None"}',
  '{"opening_statement": "I keep getting thrush. The cream works but it comes back. Is there something wrong with me?", "freely_given_history": {"presenting_complaint": "Recurrent thrush.", "ice": {"ideas": "Worried about diabetes or immune", "concerns": "Embarrassing", "expectations": "Prevention"}}, "history_on_direct_questioning": {"diabetes": "No", "antibiotics": "Occasional", "hygiene": "Normal"}}',
  'Embarrassed but articulate. Wants practical advice.',
  'full', 720, 'medium',
  ARRAY['Recurrent thrush', 'Exclude diabetes', 'Maintenance fluconazole', 'Lifestyle', 'Follow-up'],
  '## Model Approach\n\n**Key:** Exclude diabetes. Consider maintenance fluconazole (e.g. weekly 6 months). Avoid irritants. Follow-up.',
  false, true,
  '{"domain1": {"title": "Domain 1: Data Gathering & Interpretation", "items": ["Established pattern", "Excluded diabetes", "Explored ICE"]}, "domain2": {"title": "Domain 2: Clinical Management (Weighted 1.5x)", "items": ["Maintenance treatment", "Lifestyle", "Follow-up"]}, "domain3": {"title": "Domain 3: Interpersonal Skills", "items": ["Sensitive", "Clear advice"]}}'
),

('Elderly Fall', 'Geriatrics', 'FC-010',
  'You are a GP. An 82-year-old woman, Mrs. Olive Walsh, has had two falls in the last month. No serious injury. Lives alone. On ramipril, bendroflumethiazide, omeprazole.',
  '{"name": "Mrs. Olive Walsh", "age": 82, "gender": "Female"}',
  '{"patient": "Mrs. Olive Walsh", "age": 82, "gender": "Female", "pmh": "Hypertension, OA", "medications": "Ramipril, Bendroflumethiazide, Omeprazole", "allergies": "None", "social_summary": "Lives alone", "family_summary": "Daughter nearby"}',
  '{"opening_statement": "I have fallen twice. I am fine but my daughter is worried. I don''t want to go into a home.", "freely_given_history": {"presenting_complaint": "Falls.", "ice": {"ideas": "Old age", "concerns": "Independence", "expectations": "Check-up"}}, "history_on_direct_questioning": {"syncope": "No", "medication": "Takes all", "vision": "Cataracts", "home": "Stairs"}}',
  'Worried about independence. Reassured by falls assessment and practical advice.',
  'full', 720, 'medium',
  ARRAY['Falls assessment', 'Postural BP', 'Medication review', 'Vision', 'Safety'],
  '## Model Approach\n\n**Key:** Falls assessment. Lying/standing BP. Review diuretics/antihypertensives. Vision, home hazards. Refer to falls service if needed. Reassure about independence.',
  false, true,
  '{"domain1": {"title": "Domain 1: Data Gathering & Interpretation", "items": ["Established falls", "Medications", "Explored ICE"]}, "domain2": {"title": "Domain 2: Clinical Management (Weighted 1.5x)", "items": ["Falls assessment", "Medication review", "Referral if needed"]}, "domain3": {"title": "Domain 3: Interpersonal Skills", "items": ["Empathy", "Reassurance about independence"]}}'
);

-- FC-011 to FC-050: 40 more full cases (single INSERT)
INSERT INTO sca_cases (
  title, category, category_code, scenario, patient_info, case_notes, actor_info, actor_behaviour,
  case_type, time_limit, difficulty, key_points, model_answer, is_pro, published, marking_criteria
) VALUES
('Acne in Teenager', 'Dermatology', 'FC-011', 'You are a GP. A 16-year-old boy, Jack, has had facial acne for 6 months. Tried benzoyl peroxide. Wants something stronger.', '{"name": "Jack", "age": 16, "gender": "Male"}', '{"patient": "Jack", "age": 16, "gender": "Male", "pmh": "None", "medications": "None", "allergies": "None", "social_summary": "School", "family_summary": "None"}', '{"opening_statement": "My spots are getting worse. The gel did not help much. Can I get something stronger?", "freely_given_history": {"presenting_complaint": "Acne.", "ice": {"ideas": "Wants Roaccutane", "concerns": "Scarring", "expectations": "Clear skin"}}, "history_on_direct_questioning": {"severity": "Moderate", "topical": "Tried 3 months"}}', 'Teenager, a bit self-conscious. Wants clear plan.', 'full', 720, 'easy', ARRAY['Severity', 'Topical vs oral', 'Antibiotic vs isotretinoin', 'Expectations'], '## Model Approach\n\n**Key:** Assess severity. Topical retinoid + ab. Oral antibiotic if moderate. Isotretinoin only if severe/referral. Expectations.', false, true, '{"domain1": {"title": "Domain 1", "items": ["Established complaint", "Severity", "Explored ICE"]}, "domain2": {"title": "Domain 2", "items": ["Stepped treatment", "Referral if needed"]}, "domain3": {"title": "Domain 3", "items": ["Empathy", "Clear advice"]}}'),
('Asthma Review', 'Respiratory', 'FC-012', 'You are a GP. A 35-year-old woman, Ms. Anna Bell, is here for asthma review. Uses salbutamol 3–4 times per week. No preventer.', '{"name": "Ms. Anna Bell", "age": 35, "gender": "Female"}', '{"patient": "Ms. Anna Bell", "age": 35, "gender": "Female", "pmh": "Asthma", "medications": "Salbutamol PRN", "allergies": "None", "social_summary": "Teacher, non-smoker", "family_summary": "None"}', '{"opening_statement": "I use my blue inhaler most days. The nurse said I might need a preventer. What do you think?", "freely_given_history": {"presenting_complaint": "Frequent salbutamol use.", "ice": {"ideas": "Worried about steroids", "concerns": "Side effects", "expectations": "Clear plan"}}, "history_on_direct_questioning": {"symptoms": "Cough, wheeze", "night_waking": "Rarely", "peak_flow": "Not measured"}}', 'Cooperative. Wants to avoid attacks.', 'full', 720, 'easy', ARRAY['Control', 'Preventer', 'Technique', 'Action plan'], '## Model Approach\n\n**Key:** Assess control. Add ICS if using SABA >2/week. Check technique. Written action plan.', false, true, '{"domain1": {"title": "Domain 1", "items": ["Control", "Symptoms", "ICE"]}, "domain2": {"title": "Domain 2", "items": ["Preventer", "Action plan"]}, "domain3": {"title": "Domain 3", "items": ["Clear advice"]}}'),
('Breast Lump', 'Women''s Health', 'FC-013', 'You are a GP. A 48-year-old woman, Mrs. Carol Dean, has found a lump in her left breast 1 week ago. No pain. Periods regular.', '{"name": "Mrs. Carol Dean", "age": 48, "gender": "Female"}', '{"patient": "Mrs. Carol Dean", "age": 48, "gender": "Female", "pmh": "None", "medications": "None", "allergies": "None", "social_summary": "Office job", "family_summary": "No breast cancer"}', '{"opening_statement": "I found a lump last week. I am scared it might be cancer. What happens next?", "freely_given_history": {"presenting_complaint": "Breast lump.", "ice": {"ideas": "Worried about cancer", "concerns": "Waiting", "expectations": "Referral"}}, "history_on_direct_questioning": {"pain": "No", "nipple": "No change", "family": "None"}}', 'Anxious. Relieved by clear 2WW pathway.', 'full', 720, 'medium', ARRAY['2WW breast', 'Examination', 'Triple assessment', 'Safety-netting'], '## Model Approach\n\n**Key:** 2WW breast referral. Examine if competent. Don''t reassure without referral. Safety-net.', false, true, '{"domain1": {"title": "Domain 1", "items": ["History", "Examination", "ICE"]}, "domain2": {"title": "Domain 2", "items": ["2WW referral", "Safety-netting"]}, "domain3": {"title": "Domain 3", "items": ["Empathy", "Reassurance"]}}'),
('COPD Exacerbation', 'Respiratory', 'FC-014', 'You are a GP. A 68-year-old man, Mr. Eric Fox, has COPD. Increased cough, green sputum, breathlessness for 3 days. No fever.', '{"name": "Mr. Eric Fox", "age": 68, "gender": "Male"}', '{"patient": "Mr. Eric Fox", "age": 68, "gender": "Male", "pmh": "COPD", "medications": "Seretide, Tiotropium", "allergies": "None", "social_summary": "Ex-smoker", "family_summary": "None"}', '{"opening_statement": "I am more breathless and coughing up green phlegm. I have my rescue pack. Should I start it?", "freely_given_history": {"presenting_complaint": "Exacerbation.", "ice": {"ideas": "Infection", "concerns": "Hospital", "expectations": "Antibiotics"}}, "history_on_direct_questioning": {"fever": "No", "respiratory_rate": "Increased", "sats": "Not measured"}}', 'Breathless but coherent. Wants to avoid hospital.', 'full', 720, 'medium', ARRAY['Exacerbation', 'Antibiotics and steroids', 'Rescue pack', 'Hospital criteria'], '## Model Approach\n\n**Key:** Antibiotics + steroids if purulent. Check rescue pack. Hospital if severe. Safety-net.', false, true, '{"domain1": {"title": "Domain 1", "items": ["Severity", "Symptoms", "ICE"]}, "domain2": {"title": "Domain 2", "items": ["Antibiotics", "Steroids", "Safety-netting"]}, "domain3": {"title": "Domain 3", "items": ["Empathy"]}}'),
('Depression Follow-up', 'Mental Health', 'FC-015', 'You are a GP. A 42-year-old man, Mr. Gary Hill, started sertraline 6 weeks ago for depression. Mood a bit better but still low. No suicidal thoughts.', '{"name": "Mr. Gary Hill", "age": 42, "gender": "Male"}', '{"patient": "Mr. Gary Hill", "age": 42, "gender": "Male", "pmh": "Depression", "medications": "Sertraline 50mg", "allergies": "None", "social_summary": "Unemployed", "family_summary": "None"}', '{"opening_statement": "I am a bit better but still not right. Should I increase the dose or wait?", "freely_given_history": {"presenting_complaint": "Partial response.", "ice": {"ideas": "Wants to get better", "concerns": "Side effects", "expectations": "Dose or time"}}, "history_on_direct_questioning": {"mood": "Improved", "risk": "No SI", "sleep": "Better"}}', 'Low but engaged. Wants clear plan.', 'full', 720, 'easy', ARRAY['Response', 'Dose increase', 'Psychological', 'Safety'], '## Model Approach\n\n**Key:** Partial response – consider dose increase or wait. Psychological support. Risk assessment. Follow-up.', false, true, '{"domain1": {"title": "Domain 1", "items": ["Mood", "Risk", "ICE"]}, "domain2": {"title": "Domain 2", "items": ["Dose", "Support", "Follow-up"]}, "domain3": {"title": "Domain 3", "items": ["Empathy"]}}'),
('DVT Query', 'Vascular', 'FC-016', 'You are a GP. A 55-year-old woman, Mrs. Irene Jones, has a swollen, painful left calf for 2 days. No recent travel. No fever.', '{"name": "Mrs. Irene Jones", "age": 55, "gender": "Female"}', '{"patient": "Mrs. Irene Jones", "age": 55, "gender": "Female", "pmh": "None", "medications": "None", "allergies": "None", "social_summary": "Office job", "family_summary": "None"}', '{"opening_statement": "My calf is swollen and hurts. I read about DVT. Could it be that?", "freely_given_history": {"presenting_complaint": "Swollen calf.", "ice": {"ideas": "DVT", "concerns": "Blood clot", "expectations": "Tests"}}, "history_on_direct_questioning": {"wells": "Some risk", "redness": "Mild", "chest": "No"}}', 'Anxious. Wants same-day assessment.', 'full', 720, 'medium', ARRAY['Wells score', 'D-dimer vs scan', 'Referral', 'Safety'], '## Model Approach\n\n**Key:** Wells score. Refer for imaging/anticoagulation if likely DVT. Don''t delay. Safety-net PE.', false, true, '{"domain1": {"title": "Domain 1", "items": ["History", "Wells", "ICE"]}, "domain2": {"title": "Domain 2", "items": ["Referral", "Safety-netting"]}, "domain3": {"title": "Domain 3", "items": ["Reassurance"]}}'),
('Erectile Dysfunction', 'Men''s Health', 'FC-017', 'You are a GP. A 58-year-old man, Mr. Ken Lane, has had erectile dysfunction for 6 months. Embarrassed. On amlodipine for BP. No diabetes.', '{"name": "Mr. Ken Lane", "age": 58, "gender": "Male"}', '{"patient": "Mr. Ken Lane", "age": 58, "gender": "Male", "pmh": "Hypertension", "medications": "Amlodipine", "allergies": "None", "social_summary": "Married", "family_summary": "None"}', '{"opening_statement": "I have been having trouble down below for a while. I find it hard to talk about. Is there a pill?", "freely_given_history": {"presenting_complaint": "ED.", "ice": {"ideas": "Age", "concerns": "Relationship", "expectations": "Treatment"}}, "history_on_direct_questioning": {"gradual": "Yes", "morning_erection": "Rare", "cardiovascular": "Hypertension"}}', 'Embarrassed. Relieved by matter-of-fact approach.', 'full', 720, 'easy', ARRAY['Cause', 'PDE5i', 'Cardiovascular', 'Relationship'], '## Model Approach\n\n**Key:** Exclude organic cause. PDE5i if appropriate. Cardiovascular risk. Sensitive approach.', false, true, '{"domain1": {"title": "Domain 1", "items": ["History", "ICE", "Sensitive"]}, "domain2": {"title": "Domain 2", "items": ["PDE5i", "Contraindications"]}, "domain3": {"title": "Domain 3", "items": ["Sensitive", "Non-judgmental"]}}'),
('Fatigue and Anaemia', 'Haematology', 'FC-018', 'You are a GP. A 38-year-old woman, Ms. Lucy Moss, has been tired for 3 months. Hb 98 on recent bloods. Periods heavy. No other symptoms.', '{"name": "Ms. Lucy Moss", "age": 38, "gender": "Female"}', '{"patient": "Ms. Lucy Moss", "age": 38, "gender": "Female", "pmh": "None", "medications": "None", "allergies": "None", "social_summary": "Teacher", "family_summary": "None"}', '{"opening_statement": "I am exhausted. The nurse said I am anaemic. Why and what can I do?", "freely_given_history": {"presenting_complaint": "Fatigue, anaemia.", "ice": {"ideas": "Diet", "concerns": "Serious?", "expectations": "Iron"}}, "history_on_direct_questioning": {"periods": "Heavy", "diet": "Normal", "blood_loss": "No"}}', 'Tired but engaged. Wants cause and treatment.', 'full', 720, 'easy', ARRAY['Cause', 'Iron', 'Menorrhagia', 'Follow-up'], '## Model Approach\n\n**Key:** Likely iron deficiency from menorrhagia. Iron supplementation. Consider cause of menorrhagia. Repeat FBC.', false, true, '{"domain1": {"title": "Domain 1", "items": ["History", "Menstrual", "ICE"]}, "domain2": {"title": "Domain 2", "items": ["Iron", "Menorrhagia", "Follow-up"]}, "domain3": {"title": "Domain 3", "items": ["Empathy"]}}'),
('Gout Attack', 'Musculoskeletal', 'FC-019', 'You are a GP. A 62-year-old man, Mr. Neil Owen, has a hot, swollen first MTP joint for 2 days. Had gout before. On allopurinol. Not taken for 2 weeks.', '{"name": "Mr. Neil Owen", "age": 62, "gender": "Male"}', '{"patient": "Mr. Neil Owen", "age": 62, "gender": "Male", "pmh": "Gout", "medications": "Allopurinol (stopped)", "allergies": "None", "social_summary": "Drinks 15 units/week", "family_summary": "None"}', '{"opening_statement": "My toe is killing me again. I ran out of allopurinol. I need something for the pain.", "freely_given_history": {"presenting_complaint": "Acute gout.", "ice": {"ideas": "Gout", "concerns": "Recurrence", "expectations": "Pain relief"}}, "history_on_direct_questioning": {"compliance": "Stopped allopurinol", "diet": "Alcohol", "renal": "No"}}', 'In pain. Wants quick relief.', 'full', 720, 'easy', ARRAY['Acute gout', 'NSAID/colchicine', 'Restart allopurinol', 'Lifestyle'], '## Model Approach\n\n**Key:** Treat acute attack (NSAID or colchicine). Restart allopurinol after settled. Lifestyle. Follow-up.', false, true, '{"domain1": {"title": "Domain 1", "items": ["History", "Compliance", "ICE"]}, "domain2": {"title": "Domain 2", "items": ["Acute treatment", "Allopurinol"]}, "domain3": {"title": "Domain 3", "items": ["Empathy"]}}'),
('Heartburn', 'Gastroenterology', 'FC-020', 'You are a GP. A 45-year-old man, Mr. Oliver Page, has had heartburn for 2 months. Worse after meals. No alarm symptoms. Wants something stronger than Gaviscon.', '{"name": "Mr. Oliver Page", "age": 45, "gender": "Male"}', '{"patient": "Mr. Oliver Page", "age": 45, "gender": "Male", "pmh": "None", "medications": "None", "allergies": "None", "social_summary": "Overweight, eats late", "family_summary": "None"}', '{"opening_statement": "I get burning after meals. Gaviscon helps a bit. I want something that works properly.", "freely_given_history": {"presenting_complaint": "Heartburn.", "ice": {"ideas": "Stomach", "concerns": "Cancer?", "expectations": "PPI"}}, "history_on_direct_questioning": {"dysphagia": "No", "weight_loss": "No", "alarm": "None"}}', 'Cooperative. Wants effective treatment.', 'full', 720, 'easy', ARRAY['GORD', 'PPI', 'Lifestyle', 'Safety-netting'], '## Model Approach\n\n**Key:** PPI trial. Lifestyle (weight, meals). Red flags: dysphagia, weight loss. Safety-net. Review.', false, true, '{"domain1": {"title": "Domain 1", "items": ["History", "Alarm", "ICE"]}, "domain2": {"title": "Domain 2", "items": ["PPI", "Lifestyle", "Safety-netting"]}, "domain3": {"title": "Domain 3", "items": ["Clear advice"]}}'),

('Insomnia and Anxiety', 'Mental Health', 'FC-021', 'You are a GP. A 32-year-old woman, Ms. Paula Quinn, has had insomnia and anxiety for 2 months. Stressed at work. Wants sleeping tablets.', '{"name": "Ms. Paula Quinn", "age": 32, "gender": "Female"}', '{"patient": "Ms. Paula Quinn", "age": 32, "gender": "Female", "pmh": "None", "medications": "None", "allergies": "None", "social_summary": "Manager", "family_summary": "None"}', '{"opening_statement": "I cannot sleep. I lie there for hours. I need something to help.", "freely_given_history": {"presenting_complaint": "Insomnia, anxiety.", "ice": {"ideas": "Stress", "concerns": "Tablets", "expectations": "Short-term help"}}, "history_on_direct_questioning": {"caffeine": "Coffee until 4pm", "routine": "Variable", "mood": "Anxious"}}', 'Anxious. Wants quick fix but receptive to CBT.', 'full', 720, 'easy', ARRAY['Sleep hygiene', 'CBT-I', 'Short-term hypnotic', 'Anxiety'], '## Model Approach\n\n**Key:** Sleep hygiene, address anxiety. CBT-I first. Hypnotic short-term only. Safety-net.', false, true, '{"domain1": {"title": "Domain 1", "items": ["Sleep", "Anxiety", "ICE"]}, "domain2": {"title": "Domain 2", "items": ["Sleep hygiene", "Limited hypnotic"]}, "domain3": {"title": "Domain 3", "items": ["Empathy"]}}'),
('Knee Pain OA', 'Musculoskeletal', 'FC-022', 'You are a GP. A 68-year-old woman, Mrs. Rita Shaw, has bilateral knee pain for 6 months. Worse on stairs. BMI 31. X-ray 1 year ago showed OA.', '{"name": "Mrs. Rita Shaw", "age": 68, "gender": "Female"}', '{"patient": "Mrs. Rita Shaw", "age": 68, "gender": "Female", "pmh": "Hypertension", "medications": "Amlodipine", "allergies": "None", "social_summary": "Retired", "family_summary": "None"}', '{"opening_statement": "My knees are getting worse. I can hardly do the stairs. Do I need a replacement?", "freely_given_history": {"presenting_complaint": "Knee pain.", "ice": {"ideas": "Wear and tear", "concerns": "Surgery", "expectations": "Pain relief"}}, "history_on_direct_questioning": {"swelling": "Mild", "locking": "No", "red_flags": "No"}}', 'Realistic. Wants to stay active.', 'full', 720, 'easy', ARRAY['OA', 'Weight', 'Exercise', 'Analgesia', 'Referral'], '## Model Approach\n\n**Key:** Weight loss, exercise, analgesia, topical NSAID. Physio. Refer if severe. Safety-net.', false, true, '{"domain1": {"title": "Domain 1", "items": ["History", "ICE"]}, "domain2": {"title": "Domain 2", "items": ["Lifestyle", "Analgesia", "Referral"]}, "domain3": {"title": "Domain 3", "items": ["Empathy"]}}'),
('Low Back Pain with Sciatica', 'Musculoskeletal', 'FC-023', 'You are a GP. A 52-year-old man, Mr. Sam Todd, has had low back pain with right leg pain for 3 weeks. Leg pain to calf. No bladder/bowel symptoms.', '{"name": "Mr. Sam Todd", "age": 52, "gender": "Male"}', '{"patient": "Mr. Sam Todd", "age": 52, "gender": "Male", "pmh": "None", "medications": "Ibuprofen", "allergies": "None", "social_summary": "Builder", "family_summary": "None"}', '{"opening_statement": "My back and leg are killing me. I cannot work. Is it a slipped disc?", "freely_given_history": {"presenting_complaint": "Back and leg pain.", "ice": {"ideas": "Disc", "concerns": "Surgery", "expectations": "Treatment"}}, "history_on_direct_questioning": {"cauda_equina": "No", "weakness": "No", "duration": "3 weeks"}}', 'In pain. Wants to avoid surgery.', 'full', 720, 'medium', ARRAY['Sciatica', 'Red flags', 'Analgesia', 'Physio', 'Safety'], '## Model Approach\n\n**Key:** Exclude cauda equina. Analgesia, physio. Most improve. Refer if severe/prolonged. Safety-net.', false, true, '{"domain1": {"title": "Domain 1", "items": ["History", "Red flags", "ICE"]}, "domain2": {"title": "Domain 2", "items": ["Analgesia", "Physio", "Safety-netting"]}, "domain3": {"title": "Domain 3", "items": ["Empathy"]}}'),
('Menopausal Symptoms', 'Women''s Health', 'FC-024', 'You are a GP. A 51-year-old woman, Mrs. Tina Vale, has had hot flushes and night sweats for 6 months. Periods stopped 1 year ago. Wants to know about HRT.', '{"name": "Mrs. Tina Vale", "age": 51, "gender": "Female"}', '{"patient": "Mrs. Tina Vale", "age": 51, "gender": "Female", "pmh": "None", "medications": "None", "allergies": "None", "social_summary": "Teacher", "family_summary": "Mother had breast cancer at 70"}', '{"opening_statement": "I am having terrible flushes. I want to know about HRT. My mum had breast cancer – is it safe?", "freely_given_history": {"presenting_complaint": "Hot flushes.", "ice": {"ideas": "Menopause", "concerns": "Breast cancer", "expectations": "HRT"}}, "history_on_direct_questioning": {"contraindications": "None", "VTE": "No", "bleeding": "None"}}', 'Anxious about risk. Wants balanced discussion.', 'full', 720, 'medium', ARRAY['HRT benefits/risks', 'Formulation', 'Breast cancer', 'Shared decision'], '## Model Approach\n\n**Key:** Discuss HRT benefits and risks. Transdermal if VTE risk. Breast cancer: small increased risk, individualise. Shared decision.', false, true, '{"domain1": {"title": "Domain 1", "items": ["Symptoms", "Contraindications", "ICE"]}, "domain2": {"title": "Domain 2", "items": ["HRT discussion", "Shared decision"]}, "domain3": {"title": "Domain 3", "items": ["Empathy", "Clear explanation"]}}'),
('New AF', 'Cardiology', 'FC-025', 'You are a GP. A 72-year-old man, Mr. Victor Webb, has an irregular pulse at routine check. Asymptomatic. BP 150/92. No stroke history.', '{"name": "Mr. Victor Webb", "age": 72, "gender": "Male"}', '{"patient": "Mr. Victor Webb", "age": 72, "gender": "Male", "pmh": "Hypertension", "medications": "Amlodipine", "allergies": "None", "social_summary": "Retired", "family_summary": "None"}', '{"opening_statement": "The nurse said my pulse is irregular. What does that mean? Do I need treatment?", "freely_given_history": {"presenting_complaint": "Irregular pulse.", "ice": {"ideas": "Heart", "concerns": "Stroke", "expectations": "Explanation"}}, "history_on_direct_questioning": {"palpitations": "No", "syncope": "No", "bleeding": "No"}}', 'Worried. Wants clear plan.', 'full', 720, 'hard', ARRAY['ECG', 'CHA2DS2-VASc', 'Anticoagulation', 'Rate control'], '## Model Approach\n\n**Key:** Confirm AF with ECG. CHA2DS2-VASc for stroke risk; anticoagulate if indicated. Rate control if symptomatic. Refer/cardiology.', false, true, '{"domain1": {"title": "Domain 1", "items": ["History", "Stroke risk", "ICE"]}, "domain2": {"title": "Domain 2", "items": ["Anticoagulation", "Rate", "Referral"]}, "domain3": {"title": "Domain 3", "items": ["Clear explanation"]}}'),
('Obesity and Weight', 'General Practice', 'FC-026', 'You are a GP. A 44-year-old woman, Ms. Wendy York, wants to lose weight. BMI 36. Has tried diets. Wants to know about weight loss medication.', '{"name": "Ms. Wendy York", "age": 44, "gender": "Female"}', '{"patient": "Ms. Wendy York", "age": 44, "gender": "Female", "pmh": "None", "medications": "None", "allergies": "None", "social_summary": "Office job", "family_summary": "None"}', '{"opening_statement": "I have tried everything. I have heard about tablets for weight. Can I get them?", "freely_given_history": {"presenting_complaint": "Weight.", "ice": {"ideas": "Metabolism", "concerns": "Health", "expectations": "Medication"}}, "history_on_direct_questioning": {"comorbidities": "None", "diet": "Tried many", "exercise": "Little"}}', 'Frustrated. Wants option beyond diet.', 'full', 720, 'medium', ARRAY['Lifestyle', 'GLP-1 criteria', 'Comorbidities', 'Expectations'], '## Model Approach\n\n**Key:** Lifestyle first. Weight loss medication (e.g. GLP-1) if BMI/ criteria met. Set expectations. Comorbidities.', false, true, '{"domain1": {"title": "Domain 1", "items": ["History", "ICE"]}, "domain2": {"title": "Domain 2", "items": ["Lifestyle", "Medication criteria"]}, "domain3": {"title": "Domain 3", "items": ["Non-judgmental"]}}'),
('Postnatal Low Mood', 'Mental Health', 'FC-027', 'You are a GP. A 30-year-old woman, Ms. Zoe Adams, had a baby 4 months ago. Low mood, tearful, poor sleep. No thoughts of harm to baby. Partner supportive.', '{"name": "Ms. Zoe Adams", "age": 30, "gender": "Female"}', '{"patient": "Ms. Zoe Adams", "age": 30, "gender": "Female", "pmh": "None", "medications": "None", "allergies": "None", "social_summary": "First baby", "family_summary": "None"}', '{"opening_statement": "I have been really low since the baby. I cry all the time. I am scared it is postnatal depression.", "freely_given_history": {"presenting_complaint": "Low mood.", "ice": {"ideas": "Postnatal depression", "concerns": "Baby", "expectations": "Help"}}, "history_on_direct_questioning": {"risk": "No harm", "support": "Partner", "sleep": "Poor"}}', 'Tearful. Relieved by validation and plan.', 'full', 720, 'medium', ARRAY['Postnatal depression', 'Risk', 'Treatment', 'Support'], '## Model Approach\n\n**Key:** Assess severity and risk. SSRI if moderate/severe. Psychological support. Safety-net. Involve partner if appropriate.', false, true, '{"domain1": {"title": "Domain 1", "items": ["Mood", "Risk", "ICE"]}, "domain2": {"title": "Domain 2", "items": ["Treatment", "Support", "Safety"]}, "domain3": {"title": "Domain 3", "items": ["Empathy", "Validation"]}}'),
('Rash in Child', 'Paediatrics', 'FC-028', 'You are a GP. Mother of 3-year-old Ben has brought him in with a rash for 2 days. Started on trunk, spreading. No fever. Child well.', '{"name": "Ben", "age": 3, "gender": "Male"}', '{"patient": "Ben", "age": 3, "gender": "Male", "pmh": "None", "medications": "None", "allergies": "None", "social_summary": "Nursery", "family_summary": "None"}', '{"opening_statement": "He has this rash. It is spreading. Is it meningitis? He seems fine in himself.", "freely_given_history": {"presenting_complaint": "Rash.", "ice": {"ideas": "Infection", "concerns": "Meningitis", "expectations": "Diagnosis"}}, "history_on_direct_questioning": {"fever": "No", "non_blanching": "Check", "viral": "Cold last week"}}', 'Mother anxious. Relieved if benign explanation.', 'full', 720, 'medium', ARRAY['Rash type', 'Non-blanching', 'Viral vs serious', 'Safety-netting'], '## Model Approach\n\n**Key:** Describe rash; non-blanching? Viral exanthem vs meningococcal. If non-blanching or unwell – urgent. Safety-net.', false, true, '{"domain1": {"title": "Domain 1", "items": ["Rash", "Systemic", "ICE"]}, "domain2": {"title": "Domain 2", "items": ["Diagnosis", "Safety-netting"]}, "domain3": {"title": "Domain 3", "items": ["Parental reassurance"]}}'),
('Statin Intolerance', 'Cardiovascular', 'FC-029', 'You are a GP. A 64-year-old man, Mr. Alan Bates, stopped atorvastatin 2 months ago due to muscle aches. CV risk high. Wants to know options.', '{"name": "Mr. Alan Bates", "age": 64, "gender": "Male"}', '{"patient": "Mr. Alan Bates", "age": 64, "gender": "Male", "pmh": "IHD", "medications": "Aspirin, Ramipril", "allergies": "None", "social_summary": "Retired", "family_summary": "None"}', '{"opening_statement": "I had to stop the statin – my legs ached. But I know I need something. What can I do?", "freely_given_history": {"presenting_complaint": "Statin intolerance.", "ice": {"ideas": "Side effect", "concerns": "Heart risk", "expectations": "Alternative"}}, "history_on_direct_questioning": {"CK": "Not checked", "timing": "Aches after 2 years"}}', 'Willing to try alternative. High risk.', 'full', 720, 'medium', ARRAY['CK', 'Alternatives', 'Ezetimibe', 'Risk discussion'], '## Model Approach\n\n**Key:** Check CK. Try alternate statin, lower dose, or ezetimibe. Don''t leave high risk untreated. Follow-up.', false, true, '{"domain1": {"title": "Domain 1", "items": ["History", "CK", "ICE"]}, "domain2": {"title": "Domain 2", "items": ["Alternatives", "Risk"]}, "domain3": {"title": "Domain 3", "items": ["Shared decision"]}}'),
('Thyroid Nodule', 'Endocrinology', 'FC-030', 'You are a GP. A 46-year-old woman, Mrs. Beth Cole, has noticed a lump in her neck for 2 weeks. No pain, no swallowing difficulty. TFTs normal 1 year ago.', '{"name": "Mrs. Beth Cole", "age": 46, "gender": "Female"}', '{"patient": "Mrs. Beth Cole", "age": 46, "gender": "Female", "pmh": "None", "medications": "None", "allergies": "None", "social_summary": "Teacher", "family_summary": "None"}', '{"opening_statement": "I have a lump in my neck. I am worried it might be cancer. What should I do?", "freely_given_history": {"presenting_complaint": "Neck lump.", "ice": {"ideas": "Thyroid or cancer", "concerns": "Cancer", "expectations": "Scan or referral"}}, "history_on_direct_questioning": {"tfts": "Normal", "growth": "2 weeks", "red_flags": "No"}}', 'Anxious. Wants clear pathway.', 'full', 720, 'medium', ARRAY['Thyroid exam', 'TFTs', 'USS', '2WW if concern'], '## Model Approach\n\n**Key:** Examine thyroid. Check TFTs. USS thyroid. 2WW if hard, fixed, nodes. Reassure if benign; arrange USS.', false, true, '{"domain1": {"title": "Domain 1", "items": ["History", "Examination", "ICE"]}, "domain2": {"title": "Domain 2", "items": ["TFTs", "USS", "Referral"]}, "domain3": {"title": "Domain 3", "items": ["Reassurance"]}}'),

('UTI in Woman', 'Urology', 'FC-031', 'You are a GP. A 28-year-old woman, Ms. Carol Dean, has dysuria and frequency for 2 days. No fever. No vaginal discharge. First UTI in 2 years.', '{"name": "Ms. Carol Dean", "age": 28, "gender": "Female"}', '{"patient": "Ms. Carol Dean", "age": 28, "gender": "Female", "pmh": "None", "medications": "None", "allergies": "None", "social_summary": "Teacher", "family_summary": "None"}', '{"opening_statement": "It hurts when I pass water. I need antibiotics.", "freely_given_history": {"presenting_complaint": "Dysuria.", "ice": {"ideas": "Water infection", "concerns": "Kidney", "expectations": "Antibiotics"}}, "history_on_direct_questioning": {"pregnancy": "No", "vaginal": "No", "fever": "No"}}', 'Uncomfortable. Wants quick treatment.', 'full', 720, 'easy', ARRAY['UTI', 'Dipstick', 'Antibiotics', 'Safety-netting'], '## Model Approach\n\n**Key:** Dipstick; treat if positive. Nitrofurantoin or trimethoprim. Safety-net: fever, flank pain. Consider MSU if recurrent.', false, true, '{"domain1": {"title": "Domain 1", "items": ["History", "ICE"]}, "domain2": {"title": "Domain 2", "items": ["Antibiotics", "Safety-netting"]}, "domain3": {"title": "Domain 3", "items": ["Empathy"]}}'),
('Vaginal Bleeding Post-Menopause', 'Women''s Health', 'FC-032', 'You are a GP. A 58-year-old woman, Mrs. Diana Evans, has had vaginal bleeding for 1 week. Menopause 5 years ago. No HRT. No pain.', '{"name": "Mrs. Diana Evans", "age": 58, "gender": "Female"}', '{"patient": "Mrs. Diana Evans", "age": 58, "gender": "Female", "pmh": "None", "medications": "None", "allergies": "None", "social_summary": "Retired", "family_summary": "None"}', '{"opening_statement": "I have started bleeding again. I thought I was past that. Is it serious?", "freely_given_history": {"presenting_complaint": "PMB.", "ice": {"ideas": "Cancer", "concerns": "Serious", "expectations": "Referral"}}, "history_on_direct_questioning": {"amount": "Moderate", "pain": "No", "weight_loss": "No"}}', 'Anxious. Wants urgent referral.', 'full', 720, 'hard', ARRAY['PMB', '2WW gynae', 'Don''t delay', 'Safety-netting'], '## Model Approach\n\n**Key:** PMB → 2WW gynaecology. Don''t reassure without referral. Safety-net.', false, true, '{"domain1": {"title": "Domain 1", "items": ["History", "ICE"]}, "domain2": {"title": "Domain 2", "items": ["2WW referral", "Safety-netting"]}, "domain3": {"title": "Domain 3", "items": ["Empathy"]}}'),
('Wheezy Child', 'Paediatrics', 'FC-033', 'You are a GP. Mother of 18-month-old Eva has brought her in with cough and wheeze for 2 days. Cold last week. No fever. Drinking. Second episode.', '{"name": "Eva", "age": 1, "gender": "Female"}', '{"patient": "Eva", "age": 1, "gender": "Female", "pmh": "None", "medications": "None", "allergies": "None", "social_summary": "At home", "family_summary": "No asthma"}', '{"opening_statement": "She is wheezy again. Last time A&E gave her an inhaler. Should I use it?", "freely_given_history": {"presenting_complaint": "Wheeze.", "ice": {"ideas": "Asthma?", "concerns": "Breathing", "expectations": "Treatment"}}, "history_on_direct_questioning": {"distress": "Mild", "feeding": "OK", "salbutamol": "Had before"}}', 'Mother anxious. Wants clear plan.', 'full', 720, 'medium', ARRAY['Viral wheeze', 'Salbutamol', 'Technique', 'Safety-netting'], '## Model Approach\n\n**Key:** Viral wheeze. Salbutamol PRN via spacer. Technique. Safety-net: severe distress, not responding.', false, true, '{"domain1": {"title": "Domain 1", "items": ["History", "Severity", "ICE"]}, "domain2": {"title": "Domain 2", "items": ["Salbutamol", "Safety-netting"]}, "domain3": {"title": "Domain 3", "items": ["Parental reassurance"]}}'),
('X-ray Request for Back', 'General Practice', 'FC-034', 'You are a GP. A 42-year-old man, Mr. Frank Green, has had low back pain for 4 weeks. No red flags. Wants an X-ray to see what is wrong.', '{"name": "Mr. Frank Green", "age": 42, "gender": "Male"}', '{"patient": "Mr. Frank Green", "age": 42, "gender": "Male", "pmh": "None", "medications": "Ibuprofen", "allergies": "None", "social_summary": "Desk job", "family_summary": "None"}', '{"opening_statement": "I want an X-ray of my back. I need to know what is wrong.", "freely_given_history": {"presenting_complaint": "Back pain.", "ice": {"ideas": "Disc", "concerns": "Serious", "expectations": "X-ray"}}, "history_on_direct_questioning": {"red_flags": "None", "tried": "Physio, ibuprofen"}}', 'Frustrated. Wants investigation.', 'full', 720, 'easy', ARRAY['NICE back pain', 'No routine imaging', 'Reassurance', 'Physio'], '## Model Approach\n\n**Key:** NICE: don''t routinely image. Reassure. Continue physio and analgesia. Red flags? Safety-net.', false, true, '{"domain1": {"title": "Domain 1", "items": ["History", "Red flags", "ICE"]}, "domain2": {"title": "Domain 2", "items": ["No imaging", "Reassurance"]}, "domain3": {"title": "Domain 3", "items": ["Clear explanation"]}}'),
('Young Person Chest Pain', 'Cardiology', 'FC-035', 'You are a GP. A 22-year-old man, Mr. Greg Hill, has had central chest pain on exertion for 1 month. No family history of sudden death. Fit. No other symptoms.', '{"name": "Mr. Greg Hill", "age": 22, "gender": "Male"}', '{"patient": "Mr. Greg Hill", "age": 22, "gender": "Male", "pmh": "None", "medications": "None", "allergies": "None", "social_summary": "Student, sporty", "family_summary": "No cardiac"}', '{"opening_statement": "I get chest tightness when I run. It goes when I stop. Could it be my heart?", "freely_given_history": {"presenting_complaint": "Exertional chest pain.", "ice": {"ideas": "Heart", "concerns": "Serious", "expectations": "Reassurance or tests"}}, "history_on_direct_questioning": {"family": "No sudden death", "syncope": "No", "character": "Tight"}}', 'Anxious. Wants exclusion of serious cause.', 'full', 720, 'medium', ARRAY['Cardiac vs non-cardiac', 'ECG', 'Family history', 'Referral if needed'], '## Model Approach\n\n**Key:** Exertional chest pain in young: consider cardiac (e.g. HOCM). ECG. Family history. Refer if concern.', false, true, '{"domain1": {"title": "Domain 1", "items": ["History", "Family", "ICE"]}, "domain2": {"title": "Domain 2", "items": ["ECG", "Referral if needed"]}, "domain3": {"title": "Domain 3", "items": ["Reassurance"]}}'),
('Zoster (Shingles)', 'Dermatology', 'FC-036', 'You are a GP. A 68-year-old woman, Mrs. Helen Innes, has a painful rash on her left chest for 3 days. Vesicles in a band. No eye involvement.', '{"name": "Mrs. Helen Innes", "age": 68, "gender": "Female"}', '{"patient": "Mrs. Helen Innes", "age": 68, "gender": "Female", "pmh": "None", "medications": "None", "allergies": "None", "social_summary": "Retired", "family_summary": "None"}', '{"opening_statement": "I have this painful rash. The pharmacist said it might be shingles. What should I do?", "freely_given_history": {"presenting_complaint": "Rash, pain.", "ice": {"ideas": "Shingles", "concerns": "Nerves", "expectations": "Treatment"}}, "history_on_direct_questioning": {"onset": "3 days", "eye": "No", "immunosuppression": "No"}}', 'In pain. Wants antiviral.', 'full', 720, 'easy', ARRAY['Shingles', 'Antiviral within 72h', 'Eye', 'Pain'], '## Model Approach\n\n**Key:** Aciclovir if within 72h. Exclude eye involvement. Analgesia. Safety-net: eye, disseminated.', false, true, '{"domain1": {"title": "Domain 1", "items": ["History", "Distribution", "ICE"]}, "domain2": {"title": "Domain 2", "items": ["Antiviral", "Safety-netting"]}, "domain3": {"title": "Domain 3", "items": ["Empathy"]}}'),
('Alcohol Concern', 'General Practice', 'FC-037', 'You are a GP. A 48-year-old man, Mr. Ian Jones, has been told his GGT is raised. Drinks 4–5 pints most nights. Says he is fine. No withdrawal symptoms.', '{"name": "Mr. Ian Jones", "age": 48, "gender": "Male"}', '{"patient": "Mr. Ian Jones", "age": 48, "gender": "Male", "pmh": "None", "medications": "None", "allergies": "None", "social_summary": "Builder", "family_summary": "None"}', '{"opening_statement": "The nurse said my liver test is up. I like a drink but I am fine. Do I need to stop?", "freely_given_history": {"presenting_complaint": "Raised GGT.", "ice": {"ideas": "Drink", "concerns": "Liver", "expectations": "Reassurance"}}, "history_on_direct_questioning": {"units": "40+/week", "CAGE": "Not done", "dependency": "No"}}', 'Defensive but will listen. Non-judgmental approach helps.', 'full', 720, 'medium', ARRAY['Alcohol history', 'CAGE', 'Harm reduction', 'Follow-up'], '## Model Approach\n\n**Key:** Quantify alcohol. CAGE. Harm reduction. Repeat LFTs. Refer if dependent or high risk.', false, true, '{"domain1": {"title": "Domain 1", "items": ["Alcohol", "CAGE", "ICE"]}, "domain2": {"title": "Domain 2", "items": ["Harm reduction", "Follow-up"]}, "domain3": {"title": "Domain 3", "items": ["Non-judgmental"]}}'),
('Blood in Stool', 'Gastroenterology', 'FC-038', 'You are a GP. A 58-year-old man, Mr. Ken Lane, has noticed blood on the toilet paper for 2 weeks. No change in bowel habit. No weight loss. No family history of bowel cancer.', '{"name": "Mr. Ken Lane", "age": 58, "gender": "Male"}', '{"patient": "Mr. Ken Lane", "age": 58, "gender": "Male", "pmh": "None", "medications": "None", "allergies": "None", "social_summary": "Office job", "family_summary": "None"}', '{"opening_statement": "I have seen blood when I go to the toilet. I am worried about cancer.", "freely_given_history": {"presenting_complaint": "Rectal bleeding.", "ice": {"ideas": "Haemorrhoids or cancer", "concerns": "Cancer", "expectations": "Referral"}}, "history_on_direct_questioning": {"change_habit": "No", "weight": "No", "screening": "Not yet"}}', 'Anxious. Wants 2WW.', 'full', 720, 'medium', ARRAY['Rectal bleeding', '2WW lower GI', 'FOBT', 'Safety-netting'], '## Model Approach\n\n**Key:** Rectal bleeding + age → 2WW lower GI. FOBT if appropriate. Don''t reassure without referral. Safety-net.', false, true, '{"domain1": {"title": "Domain 1", "items": ["History", "Red flags", "ICE"]}, "domain2": {"title": "Domain 2", "items": ["2WW referral", "Safety-netting"]}, "domain3": {"title": "Domain 3", "items": ["Empathy"]}}'),
('Contraception Switch', 'Women''s Health', 'FC-039', 'You are a GP. A 24-year-old woman, Ms. Laura Moss, has been on Microgynon for 2 years. Low mood and low libido. Wants to try something else. Non-smoker.', '{"name": "Ms. Laura Moss", "age": 24, "gender": "Female"}', '{"patient": "Ms. Laura Moss", "age": 24, "gender": "Female", "pmh": "None", "medications": "Microgynon", "allergies": "None", "social_summary": "Student", "family_summary": "None"}', '{"opening_statement": "The pill has made me feel low and I have no interest in sex. I want to change.", "freely_given_history": {"presenting_complaint": "Low mood, libido on COCP.", "ice": {"ideas": "Pill", "concerns": "Alternatives", "expectations": "Switch"}}, "history_on_direct_questioning": {"mood": "Low", "depression": "No", "alternatives": "Interested in IUS"}}', 'Relieved to discuss. Wants option that suits.', 'full', 720, 'easy', ARRAY['COCP and mood', 'Alternatives', 'IUS, implant, POP', 'Shared decision'], '## Model Approach\n\n**Key:** COCP can affect mood/libido. Alternatives: IUS, implant, POP. Shared decision. No contraindications.', false, true, '{"domain1": {"title": "Domain 1", "items": ["History", "ICE"]}, "domain2": {"title": "Domain 2", "items": ["Alternatives", "Shared decision"]}, "domain3": {"title": "Domain 3", "items": ["Non-judgmental"]}}'),
('Dysphagia', 'Gastroenterology', 'FC-040', 'You are a GP. A 72-year-old man, Mr. Norman Page, has had difficulty swallowing solids for 3 weeks. Weight loss 2 kg. No pain. Smoker 20/day for 50 years.', '{"name": "Mr. Norman Page", "age": 72, "gender": "Male"}', '{"patient": "Mr. Norman Page", "age": 72, "gender": "Male", "pmh": "None", "medications": "None", "allergies": "None", "social_summary": "Retired, smoker", "family_summary": "None"}', '{"opening_statement": "Food keeps getting stuck. I have lost a bit of weight. I am worried.", "freely_given_history": {"presenting_complaint": "Dysphagia, weight loss.", "ice": {"ideas": "Cancer", "concerns": "Serious", "expectations": "Urgent referral"}}, "history_on_direct_questioning": {"solids_vs_liquids": "Solids", "progressive": "Yes", "haemoptysis": "No"}}', 'Anxious. Wants urgent action.', 'full', 720, 'hard', ARRAY['Dysphagia', '2WW upper GI', 'Red flags', 'Don''t delay'], '## Model Approach\n\n**Key:** Dysphagia + weight loss + smoker → 2WW upper GI. Don''t delay. Safety-net.', false, true, '{"domain1": {"title": "Domain 1", "items": ["History", "Red flags", "ICE"]}, "domain2": {"title": "Domain 2", "items": ["2WW referral", "Safety-netting"]}, "domain3": {"title": "Domain 3", "items": ["Empathy"]}}'),
('Ear Pain in Adult', 'ENT', 'FC-041', 'You are a GP. A 35-year-old woman, Ms. Olivia Quinn, has had right ear pain for 3 days. No discharge. No hearing loss. Had a cold last week.', '{"name": "Ms. Olivia Quinn", "age": 35, "gender": "Female"}', '{"patient": "Ms. Olivia Quinn", "age": 35, "gender": "Female", "pmh": "None", "medications": "None", "allergies": "None", "social_summary": "Teacher", "family_summary": "None"}', '{"opening_statement": "My ear really hurts. I need something for the pain. Do I need antibiotics?", "freely_given_history": {"presenting_complaint": "Ear pain.", "ice": {"ideas": "Infection", "concerns": "Hearing", "expectations": "Treatment"}}, "history_on_direct_questioning": {"discharge": "No", "hearing": "Normal", "otalgia": "Yes"}}', 'In pain. Wants relief.', 'full', 720, 'easy', ARRAY['Otitis media vs externa', 'Analgesia', 'Antibiotics if indicated', 'Safety-netting'], '## Model Approach\n\n**Key:** Analgesia first. Otitis media: often viral. Antibiotics if severe or high risk. Otitis externa: drops. Safety-net.', false, true, '{"domain1": {"title": "Domain 1", "items": ["History", "ICE"]}, "domain2": {"title": "Domain 2", "items": ["Analgesia", "Antibiotics if needed"]}, "domain3": {"title": "Domain 3", "items": ["Empathy"]}}'),
('Follow-up Depression', 'Mental Health', 'FC-042', 'You are a GP. A 38-year-old woman, Ms. Paula Reid, has been on sertraline 8 weeks. Mood much better. Wants to know when she can stop.', '{"name": "Ms. Paula Reid", "age": 38, "gender": "Female"}', '{"patient": "Ms. Paula Reid", "age": 38, "gender": "Female", "pmh": "Depression", "medications": "Sertraline 50mg", "allergies": "None", "social_summary": "Teacher", "family_summary": "None"}', '{"opening_statement": "I feel much better. Can I stop the tablets now?", "freely_given_history": {"presenting_complaint": "Recovered.", "ice": {"ideas": "Stop soon", "concerns": "Relapse", "expectations": "When to stop"}}, "history_on_direct_questioning": {"duration": "8 weeks", "episodes": "First", "risk": "Low"}}', 'Well. Wants to come off medication.', 'full', 720, 'easy', ARRAY['Duration', 'Continue 6–12 months', 'Taper', 'Relapse'], '## Model Approach\n\n**Key:** Continue at least 6 months after remission (longer if recurrent). Taper when stopping. Relapse prevention.', false, true, '{"domain1": {"title": "Domain 1", "items": ["Mood", "ICE"]}, "domain2": {"title": "Domain 2", "items": ["Duration", "Taper plan"]}, "domain3": {"title": "Domain 3", "items": ["Clear advice"]}}'),
('Groin Lump', 'General Surgery', 'FC-043', 'You are a GP. A 55-year-old man, Mr. Quentin Ross, has noticed a lump in his right groin for 2 weeks. Reduces when lying down. No pain. No fever.', '{"name": "Mr. Quentin Ross", "age": 55, "gender": "Male"}', '{"patient": "Mr. Quentin Ross", "age": 55, "gender": "Male", "pmh": "None", "medications": "None", "allergies": "None", "social_summary": "Office job", "family_summary": "None"}', '{"opening_statement": "I have a lump in my groin. It goes away when I lie down. Is it a hernia?", "freely_given_history": {"presenting_complaint": "Groin lump.", "ice": {"ideas": "Hernia", "concerns": "Serious", "expectations": "Referral"}}, "history_on_direct_questioning": {"reducible": "Yes", "pain": "No", "bowel": "Normal"}}', 'Worried. Wants diagnosis and plan.', 'full', 720, 'easy', ARRAY['Hernia', 'Examination', 'Referral', 'Safety-netting'], '## Model Approach\n\n**Key:** Likely inguinal hernia. Examine. Refer for surgical opinion. Safety-net: strangulation.', false, true, '{"domain1": {"title": "Domain 1", "items": ["History", "Examination", "ICE"]}, "domain2": {"title": "Domain 2", "items": ["Referral", "Safety-netting"]}, "domain3": {"title": "Domain 3", "items": ["Clear explanation"]}}'),
('Haematuria', 'Urology', 'FC-044', 'You are a GP. A 62-year-old man, Mr. Robert Stone, had one episode of visible blood in urine 1 week ago. No pain. No frequency. Non-smoker. No anticoagulants.', '{"name": "Mr. Robert Stone", "age": 62, "gender": "Male"}', '{"patient": "Mr. Robert Stone", "age": 62, "gender": "Male", "pmh": "Hypertension", "medications": "Amlodipine", "allergies": "None", "social_summary": "Retired", "family_summary": "None"}', '{"opening_statement": "I passed blood in my water last week. Just once. Should I be worried?", "freely_given_history": {"presenting_complaint": "Visible haematuria.", "ice": {"ideas": "Infection?", "concerns": "Cancer", "expectations": "Tests"}}, "history_on_direct_questioning": {"pain": "No", "recurrence": "No", "smoking": "No"}}', 'Anxious. Wants 2WW.', 'full', 720, 'medium', ARRAY['Visible haematuria', '2WW urology', 'Dipstick', 'Safety-netting'], '## Model Approach\n\n**Key:** Visible haematuria → 2WW urology. Dipstick, culture. Don''t delay. Safety-net.', false, true, '{"domain1": {"title": "Domain 1", "items": ["History", "ICE"]}, "domain2": {"title": "Domain 2", "items": ["2WW referral", "Safety-netting"]}, "domain3": {"title": "Domain 3", "items": ["Empathy"]}}'),
('Indigestion and NSAIDs', 'Gastroenterology', 'FC-045', 'You are a GP. A 61-year-old man, Mr. Sam Todd, has had heartburn for 2 weeks. Takes ibuprofen daily for knee pain. No alarm symptoms.', '{"name": "Mr. Sam Todd", "age": 61, "gender": "Male"}', '{"patient": "Mr. Sam Todd", "age": 61, "gender": "Male", "pmh": "OA", "medications": "Ibuprofen 400mg TDS", "allergies": "None", "social_summary": "Retired", "family_summary": "None"}', '{"opening_statement": "My stomach has been burning. I take ibuprofen for my knee. Could that be it?", "freely_given_history": {"presenting_complaint": "Heartburn.", "ice": {"ideas": "Ibuprofen", "concerns": "Ulcer", "expectations": "PPI or stop ibuprofen"}}, "history_on_direct_questioning": {"melena": "No", "weight_loss": "No", "CV_risk": "None"}}', 'Cooperative. Wants to keep pain control.', 'full', 720, 'easy', ARRAY['NSAID and PPI', 'Alternatives', 'Red flags', 'Review'], '## Model Approach\n\n**Key:** PPI with NSAID or stop/reduce NSAID. Topical NSAID, paracetamol. Red flags. Review.', false, true, '{"domain1": {"title": "Domain 1", "items": ["History", "ICE"]}, "domain2": {"title": "Domain 2", "items": ["PPI", "NSAID review"]}, "domain3": {"title": "Domain 3", "items": ["Clear advice"]}}'),
('Joint Pain Multiple', 'Rheumatology', 'FC-046', 'You are a GP. A 58-year-old woman, Mrs. Tina Vale, has had painful, stiff hands and knees for 3 months. Worse in morning. No rash. No systemic symptoms.', '{"name": "Mrs. Tina Vale", "age": 58, "gender": "Female"}', '{"patient": "Mrs. Tina Vale", "age": 58, "gender": "Female", "pmh": "None", "medications": "Paracetamol", "allergies": "None", "social_summary": "Office job", "family_summary": "None"}', '{"opening_statement": "My hands and knees are so stiff and painful. I thought it might be arthritis. What can I do?", "freely_given_history": {"presenting_complaint": "Joint pain, stiffness.", "ice": {"ideas": "Arthritis", "concerns": "Rheumatoid", "expectations": "Treatment"}}, "history_on_direct_questioning": {"morning_stiffness": "30 min", "symmetry": "Yes", "swelling": "Mild"}}', 'Worried. Wants diagnosis.', 'full', 720, 'medium', ARRAY['OA vs inflammatory', 'Bloods', 'X-ray', 'Referral if inflammatory'], '## Model Approach\n\n**Key:** Consider OA vs inflammatory. CRP, RF if inflammatory pattern. X-ray. Refer rheumatology if inflammatory.', false, true, '{"domain1": {"title": "Domain 1", "items": ["History", "Pattern", "ICE"]}, "domain2": {"title": "Domain 2", "items": ["Bloods", "Referral if needed"]}, "domain3": {"title": "Domain 3", "items": ["Empathy"]}}'),
('Kidney Stone Follow-up', 'Urology', 'FC-047', 'You are a GP. A 45-year-old man, Mr. Victor Webb, passed a kidney stone 2 weeks ago. Had pain and haematuria. Now pain-free. Wants to know how to prevent another.', '{"name": "Mr. Victor Webb", "age": 45, "gender": "Male"}', '{"patient": "Mr. Victor Webb", "age": 45, "gender": "Male", "pmh": "None", "medications": "None", "allergies": "None", "social_summary": "Office job", "family_summary": "None"}', '{"opening_statement": "I passed a stone. I don''t want that again. What can I do?", "freely_given_history": {"presenting_complaint": "Prevention.", "ice": {"ideas": "Diet", "concerns": "Recurrence", "expectations": "Advice"}}, "history_on_direct_questioning": {"fluid": "Low", "diet": "Normal", "stone_analysis": "No"}}', 'Relieved. Wants prevention.', 'full', 720, 'easy', ARRAY['Fluid', 'Diet', 'Stone analysis if recurrent', 'Follow-up'], '## Model Approach\n\n**Key:** Increase fluid. Diet: moderate calcium, low salt. Stone analysis if recurrent. Follow-up if high risk.', false, true, '{"domain1": {"title": "Domain 1", "items": ["History", "ICE"]}, "domain2": {"title": "Domain 2", "items": ["Fluid", "Diet", "Follow-up"]}, "domain3": {"title": "Domain 3", "items": ["Clear advice"]}}'),
('Lump in Neck', 'ENT', 'FC-048', 'You are a GP. A 50-year-old woman, Mrs. Wendy York, has noticed a lump in the left side of her neck for 3 weeks. No pain. No swallowing difficulty. No fever.', '{"name": "Mrs. Wendy York", "age": 50, "gender": "Female"}', '{"patient": "Mrs. Wendy York", "age": 50, "gender": "Female", "pmh": "None", "medications": "None", "allergies": "None", "social_summary": "Teacher", "family_summary": "None"}', '{"opening_statement": "I have a lump in my neck. I am worried it might be cancer.", "freely_given_history": {"presenting_complaint": "Neck lump.", "ice": {"ideas": "Lymph node or cancer", "concerns": "Cancer", "expectations": "Referral"}}, "history_on_direct_questioning": {"duration": "3 weeks", "growth": "Stable", "throat": "No symptoms"}}', 'Anxious. Wants 2WW.', 'full', 720, 'medium', ARRAY['Neck lump', '2WW ENT/head neck', 'Examination', 'Safety-netting'], '## Model Approach\n\n**Key:** Persistent neck lump → 2WW ENT/head and neck. Examine. Don''t reassure without referral. Safety-net.', false, true, '{"domain1": {"title": "Domain 1", "items": ["History", "Examination", "ICE"]}, "domain2": {"title": "Domain 2", "items": ["2WW referral", "Safety-netting"]}, "domain3": {"title": "Domain 3", "items": ["Empathy"]}}'),
('Migraine with Aura', 'Neurology', 'FC-049', 'You are a GP. A 32-year-old woman, Ms. Zoe Adams, has had migraine with visual aura for 5 years. Wants to try preventive treatment. Uses sumatriptan for attacks.', '{"name": "Ms. Zoe Adams", "age": 32, "gender": "Female"}', '{"patient": "Ms. Zoe Adams", "age": 32, "gender": "Female", "pmh": "Migraine", "medications": "Sumatriptan PRN", "allergies": "None", "social_summary": "Teacher", "family_summary": "Mother migraine"}', '{"opening_statement": "I get migraines with flashing lights. They are more frequent now. I want to prevent them.", "freely_given_history": {"presenting_complaint": "Migraine with aura.", "ice": {"ideas": "Hormones?", "concerns": "Stroke risk", "expectations": "Prevention"}}, "history_on_direct_questioning": {"frequency": "3/month", "COCP": "No", "stroke_risk": "None"}}', 'Articulate. Wants preventive option.', 'full', 720, 'medium', ARRAY['Aura and COCP', 'Prevention', 'Propranolol/topiramate', 'Safety'], '## Model Approach\n\n**Key:** Migraine with aura: avoid COCP (stroke risk). Preventive: propranolol, topiramate. Acute: triptan. Safety-net.', false, true, '{"domain1": {"title": "Domain 1", "items": ["History", "Aura", "ICE"]}, "domain2": {"title": "Domain 2", "items": ["Prevention", "COCP caution"]}, "domain3": {"title": "Domain 3", "items": ["Clear explanation"]}}'),
('New Hypertension', 'Cardiovascular', 'FC-050', 'You are a GP. A 45-year-old man, Mr. Alan Bates, has BP 152/94 at routine check. Asymptomatic. BMI 28. Smoker 10/day. Father had stroke at 65.', '{"name": "Mr. Alan Bates", "age": 45, "gender": "Male"}', '{"patient": "Mr. Alan Bates", "age": 45, "gender": "Male", "pmh": "None", "medications": "None", "allergies": "None", "social_summary": "Office job", "family_summary": "Father stroke"}', '{"opening_statement": "The nurse said my blood pressure is high. I feel fine. Do I need tablets?", "freely_given_history": {"presenting_complaint": "Raised BP.", "ice": {"ideas": "Stress", "concerns": "Stroke", "expectations": "Lifestyle or tablets"}}, "history_on_direct_questioning": {"confirm": "Repeat BP", "lifestyle": "Poor", "kidney": "No"}}', 'Slightly defensive. Wants to avoid medication.', 'full', 720, 'medium', ARRAY['Confirm BP', 'Lifestyle', 'CV risk', 'Treatment threshold'], '## Model Approach\n\n**Key:** Confirm with ABPM/home. Lifestyle. CV risk. Treat if sustained ≥140/90 (or lower if high risk). Follow-up.', false, true, '{"domain1": {"title": "Domain 1", "items": ["BP", "Lifestyle", "ICE"]}, "domain2": {"title": "Domain 2", "items": ["Confirm", "Lifestyle", "Treatment"]}, "domain3": {"title": "Domain 3", "items": ["Clear explanation"]}}');
